/* Chapter 8 lesson and activity data. Rebuild with node src/build.mjs --module=modules/08. */
PROSE.s82a = "\n<span class=\"eyebrow\">Objective 8.2 · Part 1</span><h2>Why standalone applications stopped working</h2>\n<p class=\"lede\">No firm sat down and chose to run on nine disconnected systems. Each one was bought for a good reason, by a department with a real problem, in a year when nobody was asking what would happen once the ninth arrived.</p>\n<h3>How a firm ends up here</h3>\n<p>Companies began using information systems by fulfilling the needs of a particular business activity in a particular department. Payroll needed to issue paychecks. Accounting needed a ledger. So the firm purchased proprietary software from different software vendors, or built department-specific software, one problem at a time.</p>\n<p>Those systems focused on the specific needs of individual departments. They were not designed to communicate with the other systems in the organization; they are, in effect, speaking different languages. A system like that is a standalone application.</p>\n<p>Standalone applications are not failures. They let a department conduct its daily business activities efficiently. The trouble starts the moment somebody in one part of the firm needs information from another part of the firm.</p>\n<p>Three terms describe the situation most firms are actually in:</p>\n<ul class=\"keys\"><li><b>Standalone application</b> serves one department's needs and was never built to exchange data with the rest of the firm.</li><li><b>Legacy system</b> names an application at or beyond the end of its useful life that the business still depends on daily.</li><li><b>Best-of-breed</b> describes running independent systems that are each the strongest in their own area, chosen deliberately to keep the firm agile.</li></ul>\n<div class=\"activity\" data-activity=\"riseMatch\"></div>\n<h3>What the separation costs</h3>\n<p>Consider order entry. If the applications for inbound logistics and operations are not integrated, personnel may have to open two separate applications to verify that components are in inventory before the order can be processed. Picture it as rocks in a river: information is generated by one activity and does not flow through to the next.</p>\n<p>To use data held in separate standalone systems, the data must be reentered from one system to the next, by typing it again, copying and pasting, or downloading it into a spreadsheet. The alternative is to have a third system consolidate it, which adds a system to run rather than removing the split.</p>\n<p>Put one number on the retyping. If a clerk reenters 40 order lines a day and each takes 30 seconds, that is 20 minutes a day, or about 7 hours across a 21-day work month, spent moving data the firm already had.</p>\n<p>Joining the systems properly is not cheap either. Applications running on different computing platforms are difficult to integrate, so IS managers end up knitting together a hodgepodge of discordant proprietary applications with custom interfaces, and that integration is typically very costly.</p>\n<p>The damage lands in four places you can name out loud:</p>\n<ul class=\"keys\"><li><b>Redundancy</b> means the same fact is stored in two systems, so the firm pays twice to enter, store and update it.</li><li><b>Inconsistency</b> follows when one copy is updated and the other is not, and two departments then quote two different numbers.</li><li><b>Lost time</b> accumulates as staff reenter data and open a second application instead of doing the work they were hired to do.</li><li><b>Compliance exposure</b> grows because demonstrating conformance with standards, rules or regulations takes integrated data the firm cannot readily assemble.</li></ul>\n<div class=\"activity\" data-activity=\"riseSort\"></div>\n<h3>What an enterprise system changes</h3>\n<p>An <b>enterprise-wide information system</b>, or <b>enterprise system</b>, is an integrated suite of business applications for virtually every business process, allowing a company to integrate data across functional areas on a company-wide basis.</p>\n<p>The change that matters is not the size of the suite. Rather than storing data in separate places throughout the organization, an enterprise system uses an integrated database as a central repository common to all users. One place holds the order, the inventory figure and the invoice.</p>\n<p>That central database answers the multiple-platform problem directly, and a common user interface lets personnel share information seamlessly, no matter where the user sits or which department the user belongs to.</p>\n<div class=\"activity\" data-activity=\"riseCase\"></div>\n<h3>Which problem do you actually have</h3>\n<p>Before recommending anything, ask where the disputed fact is stored and who updates it. A department annoyed by a slow, ugly application has a different problem from a department that cannot trust the number on its screen, and the two need different remedies.</p>\n<p>Two questions separate them quickly:</p>\n<ul class=\"keys\"><li><b>Who else keeps this fact?</b> If a second system stores the same quantity, a better application on one side changes nothing.</li><li><b>What does the disagreement cost today?</b> Count the retyping, the reconciliation hours and the promises broken because a figure was stale.</li></ul>\n<p>Managers still have a genuine choice here. A best-of-breed portfolio keeps agility and lets a firm respond quickly to changes in its environment; an enterprise system trades some of that for one shared set of facts. Either way, the selection has to meet the requirements of the business and of its customers and suppliers.</p>\n<p class=\"takeaway\">Standalone applications did not stop doing what they were bought to do. They stopped working for a firm that needs one answer to a question crossing three departments, because that answer was never stored in one place.</p>\n";

ACT.riseMatch = {
  "kind": "match",
  "label": "Match",
  "title": "The symptom and the thing causing it",
  "objective": "8.2",
  "how": "Match each symptom on the left to the underlying cause on the right, then check. Read why each pairing fits.",
  "pairs": [
    {
      "l": "Two departments quote different stock figures for the same part",
      "r": "The quantity is stored twice and each copy is updated separately",
      "why": "Redundant storage becomes inconsistency the first time one copy is updated and the other is not."
    },
    {
      "l": "A clerk retypes yesterday's orders into a second application",
      "r": "Data must be reentered to move from one standalone system to the next",
      "why": "Separate systems cannot pass data between themselves, so a person carries it across by hand."
    },
    {
      "l": "Connecting two applications quotes higher than either application cost",
      "r": "Custom interfaces are needed to knit discordant proprietary platforms together",
      "why": "Applications on different computing platforms are difficult to integrate, and that integration is typically very costly."
    },
    {
      "l": "Operations opens two screens before it can accept one order",
      "r": "Inbound logistics and operations run applications that are not integrated",
      "why": "Personnel must check inventory in one application before processing the order in another."
    },
    {
      "l": "A working application is scheduled for replacement anyway",
      "r": "The application is at or beyond the end of its useful life",
      "why": "That is what makes it a legacy system; it still runs, but the firm can no longer build on it."
    }
  ]
};

ACT.riseSort = {
  "kind": "sort",
  "label": "Classify",
  "title": "Is separate data the cause, or is something else?",
  "objective": "8.2",
  "how": "Decide whether each situation is caused by data living in separate systems, then check your reasoning. You can revise and try again.",
  "buckets": [
    {
      "id": "split",
      "name": "Caused by separate data",
      "hint": "It would go away if one shared database held the fact once."
    },
    {
      "id": "other",
      "name": "A different problem entirely",
      "hint": "It would still happen on the day after every department shared one database."
    }
  ],
  "items": [
    {
      "t": "Sales and the warehouse report different quantities on hand for part A-40.",
      "b": "split",
      "why": "The same fact is stored in two systems and each department updates its own copy."
    },
    {
      "t": "A clerk retypes 120 shipment lines into accounting every Monday morning.",
      "b": "split",
      "why": "Reentry exists because the two applications cannot pass the data between themselves."
    },
    {
      "t": "The order entry date sits in one application and the invoice date in another.",
      "b": "split",
      "why": "No single record holds both ends of the span, so the elapsed time cannot be read off anywhere."
    },
    {
      "t": "The warehouse crew miscounted a shelf during the annual physical count.",
      "b": "other",
      "why": "A wrong count is a wrong count; one shared database would store the same wrong number."
    },
    {
      "t": "Two supervisors disagree about whether a rush order justifies overtime.",
      "b": "other",
      "why": "This is a management judgment about cost and service, not a question of where data sits."
    },
    {
      "t": "Freight rates rose this quarter, so shipping costs more than budgeted.",
      "b": "other",
      "why": "The price change comes from outside the firm; integrated data reports it sooner but cannot prevent it."
    }
  ]
};

ACT.riseCase = {
  "kind": "case",
  "label": "Mini case",
  "title": "Four systems, one disagreement",
  "objective": "8.2",
  "how": "Study the hypothetical case and its invented figures. Make every decision to unlock the debrief; read the explanation for each option.",
  "brief": "Alder Supply is a hypothetical parts distributor running four applications bought from four vendors over eleven years. Quantity on hand is stored in three of them, and each department updates its own copy. Sales keeps promising stock the warehouse has already shipped, and nobody can say how long an order takes end to end.",
  "facts": [
    {
      "k": "Applications in use",
      "v": "4, from 4 vendors"
    },
    {
      "k": "Where stock is stored",
      "v": "3 of the 4, each updated by its own department"
    },
    {
      "k": "Integration between them",
      "v": "None; order lines are retyped by hand"
    },
    {
      "k": "Period studied",
      "v": "One ordinary month, 640 order lines"
    }
  ],
  "exhibit": {
    "name": "What one month of disagreement cost",
    "caption": "Invented practice figures for this case only. The four lines total $6,142 for the month.",
    "headers": [
      "What happened",
      "Times in the month",
      "Cost each",
      "Month total"
    ],
    "rows": [
      [
        "Order promised from stock that was not there",
        "18",
        "$95",
        "$1,710"
      ],
      [
        "Order lines retyped from sales into accounting",
        "640",
        "$1.50",
        "$960"
      ],
      [
        "Rush freight to cover a promise stock could not keep",
        "11",
        "$240",
        "$2,640"
      ],
      [
        "Hours spent reconciling the three stock figures",
        "26",
        "$32",
        "$832"
      ]
    ]
  },
  "questions": [
    {
      "q": "Sales and the warehouse show different quantities on hand for part A-40. Which statement identifies the cause?",
      "opts": [
        "The warehouse counts its shelves less carefully than sales counts its orders.",
        "The sales application is older than the warehouse application and runs slower.",
        "The quantity sits in three systems, each updated by its own department.",
        "Both departments read one shared record, but at different times of day."
      ],
      "a": 2,
      "why": [
        "Careless counting would produce one wrong figure rather than three figures that disagree with each other.",
        "Age and speed affect how pleasant a system is to use, not whether two stored copies match.",
        "A fact stored three times and updated separately drifts apart; redundancy has become inconsistency.",
        "The facts describe three separate copies, and a single shared record is exactly what Alder lacks."
      ]
    },
    {
      "q": "A vendor offers a larger, more capable warehouse application to replace the current one. What should Alder expect about the disagreeing stock figure?",
      "opts": [
        "Rush freight falls, because a bigger application predicts demand for each part.",
        "Retyping stops, because bigger applications read the file formats other vendors write.",
        "The figure becomes correct, because the bigger application validates each entry made.",
        "The figure still disagrees, because it is stored in two other systems."
      ],
      "a": 3,
      "why": [
        "Better forecasting inside one department cannot fix a promise made from a figure another system holds.",
        "Reading a file is still reentry through a third system rather than one shared record.",
        "Validation checks the entries made in that system; it cannot reconcile a copy kept elsewhere.",
        "Replacing one of three copies leaves two, so the copies keep drifting apart exactly as before."
      ]
    },
    {
      "q": "Which change would let a supervisor answer how long an order takes from entry to invoice?",
      "opts": [
        "Ask each of the four departments to email a weekly summary of its stage.",
        "Record every stage against one order record in an integrated database.",
        "Add a report writer to the sales system that charts monthly order volume.",
        "Have accounting keep a spreadsheet of the invoice dates it issues."
      ],
      "a": 1,
      "why": [
        "Weekly summaries are consolidation by hand, and the stages still sit in four separate records.",
        "One shared record carries every stage, so the elapsed time can be read straight off it.",
        "A report reads one system's data, and the entry-to-invoice span crosses three other systems.",
        "Invoice dates give the end of the span without the order-entry date beside them."
      ]
    }
  ],
  "debrief": "Alder's $6,142 month is not a software-quality problem. Every line in the exhibit traces to one fact living in three places with three owners. A bigger application on one side of that split leaves the split intact, while an integrated database used as a central repository removes it, which is what enterprise systems were built to do."
};
