/* ===== s11a ===== */
PROSE.s11a = `
<span class="eyebrow">Section 1&ndash;1a</span>
<h2>The digital world we already live in</h2>
<p class="lede">You already know computers are everywhere. What you have probably not done is look at that fact the way a manager must: as forces deciding who gets paid well, who gets locked out, where work happens, and which enormous problems businesses get asked to help solve.</p>

<h3>Information systems are ubiquitous</h3>
<p>An <b>information system</b> is the combination of people and information technology that creates, collects, processes, stores, and distributes useful data. Something <b>ubiquitous</b> is present everywhere at once, so present you stop noticing it &mdash; which is what information systems now are, whether you see them or not. They already run in places you would not think to look:</p>
<ul class="keys">
<li><b>Shipping</b> &mdash; FedEx and UPS use them to route trucks and track packages, so the estimate on your phone comes from a system.</li>
<li><b>Retail</b> &mdash; Walgreens and Walmart use them to optimize supply chains and analyze customer tastes and preferences.</li>
<li><b>Public infrastructure</b> &mdash; cities use them for adaptive traffic control systems and variable speed limits, so a light that changes with traffic is deciding something.</li>
<li><b>Vehicles</b> &mdash; your car uses them for ignition control, airbags, park assist, and even self-driving.</li>
</ul>
<p>Some companies do not just use one; they are one. A <b>business model</b> is a summary of a business&rsquo;s strategic direction that outlines how the objectives will be achieved. Airbnb and Uber are innovative business models built on or around information systems; delete the software matching riders to drivers and no company remains, only strangers with cars.</p>
<p>Then come the systems you use on purpose:</p>
<ul class="split">
<li>Registering for classes online rather than in person.</li>
<li>Submitting work through Blackboard, Canvas, or Moodle.</li>
<li>A paycheck generated by computer and deposited automatically.</li>
<li>Algorithms built to explore your browsing and shopping habits so platforms such as Facebook or TikTok can steer you toward new interests.</li>
<li>One phone for photos, music, games, and navigation.</li>
</ul>

<h3>The post-PC era</h3>
<p>Computing used to mean walking to a machine and sitting down at it. Now connected devices, smartphones, and tablets are replacing traditional desktop and laptop computers &mdash; the <b>post-PC era</b>. Tablets began as consumer devices and are now commonplace in warehouses, showrooms, airplane cockpits, and hospitals.</p>
<p>Newer form factors do not kill older ones; they work in tandem, giving different devices to different users for different tasks, because what matters is not the device but the services and data it reaches. The same shift produced wearable computers, augmented reality devices, and smart home devices.</p>
<p>Two ordinary constraints fell away, and the activity changed with them:</p>
<ul class="keys">
<li><b>Place</b> &mdash; people once bound to a stationary PC are now bound to no particular location.</li>
<li><b>Time</b> &mdash; a workday once ran from powering the computer on to turning it off at night, and today casual tasks such as email happen at any hour in small chunks, like waiting in line at a cashier.</li>
<li><b>Activity</b> &mdash; computing was once focused primarily on automating work, and now it also provides new benefits and services and carries social and casual activity.</li>
</ul>
<p>Mobile broadband makes computing <b>instant-on</b>, and <b>cloud computing</b> &mdash; Gmail, Microsoft 365, Dropbox &mdash; keeps files reachable from whichever device you hold.</p>

<h3>The cycle runs in both directions</h3>
<p>It is tempting to assume technology arrives and society adjusts. It runs as a loop instead: changes in technology lead to societal changes, and societal changes shape technological changes. The same loop earns two names, depending on the side you describe:</p>
<ul class="keys">
<li><b>Virtuous cycle</b> &mdash; the benefit side, because communication, social networking, and online investing almost necessitate mobility and connectivity, and people have grown accustomed to checking email, posting status updates, or checking real-time stock quotes while on the go.</li>
<li><b>Vicious cycle</b> &mdash; the cost side, because work life creeps into leisure time and the fixation on being permanently &ldquo;on call&rdquo; grows.</li>
</ul>
<p>Society then pushes back on the technology: with the boundary between work and leisure blurred, employees increasingly demand devices that support both and often bring their own devices into the workplace.</p>

<h3>Knowledge workers and the knowledge society</h3>
<p>In 1959, more than 65 years ago, <b>Peter Drucker</b> predicted that information and information systems would become increasingly important, and coined the term <b>knowledge worker</b>. Knowledge workers are typically professionals who are relatively well educated and who create, modify, and/or synthesize knowledge as a fundamental part of their jobs &mdash; an analyst building a forecast, a nurse practitioner reading a chart.</p>
<p>He was right, and the advantage shows up in four places:</p>
<ul class="keys">
<li><b>Pay</b> &mdash; they are generally paid better than their agricultural and industrial counterparts.</li>
<li><b>Education</b> &mdash; they are empowered by formal education while often also possessing valuable real-world skills.</li>
<li><b>Learning</b> &mdash; they are continually learning to do their jobs better.</li>
<li><b>Bargaining power</b> &mdash; they hold much better career opportunities and far more bargaining power than workers ever had before.</li>
</ul>
<p>They make up about a quarter of the workforce in the United States and other developed nations, and their numbers are rising quickly.</p>
<p>Drucker also predicted the society they would build. Because education matters so much to knowledge workers and the firms that need them, education would become the cornerstone of a <b>knowledge society</b>, in which possessing knowledge is as important as possessing land, labor, or capital, if not more so.</p>
<p>Others call it the knowledge economy, the new economy, the digital society, the network era, or the internet era; this book simply calls it the <b>digital world</b>.</p>
<div class="card">
<p><b>What the earnings data show.</b> The most recent data from the U.S. Census Bureau&rsquo;s American Community Survey (2023 data) give median earnings for workers 25 and over:</p>
<div class="tbl-wrap"><table class="tbl"><thead><tr><th>Highest level of education</th><th>Median earnings per year</th></tr></thead><tbody>
<tr><td>Graduate or professional degree</td><td>US$86,524</td></tr>
<tr><td>Bachelor&rsquo;s degree</td><td>US$67,256</td></tr>
<tr><td>High school diploma</td><td>US$39,428</td></tr>
<tr><td>Without a high school diploma</td><td>US$31,660</td></tr>
</tbody></table></div>
<p>That gap is increasing, not closing, and a degree is often required to qualify for advancement at all.</p>
</div>
<p>Knowledge work is also leaking into occupations nobody used to file under that heading:</p>
<ul class="keys">
<li><b>The delivery driver</b> &mdash; the UPS delivery person uses global positioning system (GPS) technology to take the best route, so a system picks the route, not memory of the neighborhood.</li>
<li><b>The farmer</b> &mdash; the farmer in Iowa flies a drone to monitor soil conditions and crop yield, turning a field into data somebody must read.</li>
</ul>
<p>So the lines between &ldquo;knowledge workers&rdquo; and &ldquo;manual workers&rdquo; are blurring, to the point that almost every worker can now be considered a knowledge worker &mdash; and workers of the future need to become <b>learning workers</b>, because not the knowledge itself but the knowledge of how to learn will be of primary importance.</p>

<div class="activity" data-activity="dwQuiz1"></div>

<h3>The digital divide</h3>
<p>All of that assumes you are on the inside; not everyone is. The <b>digital divide</b> is the gap between those with access to information systems, who hold great advantages, and those without it. The chapter calls it one of the major ethical challenges facing society today, because of the strong linkage between computer literacy and a person&rsquo;s ability to compete in the digital world.</p>
<p>As the economist John Kenneth Galbraith put it, &ldquo;in the informational society, the fuel, the power, is knowledge,&rdquo; splitting society between those who have information and those who function out of ignorance.</p>
<p>The divide is not the same everywhere, and neither is the fix:</p>
<ul class="keys">
<li><b>Inside America</b> &mdash; the divide is rapidly shrinking, but people in rural communities, the elderly, people with disabilities, and minorities lag behind national averages for internet access and computer literacy.</li>
<li><b>Outside developed countries</b> &mdash; the gap gets even wider and the obstacles much harder, particularly where infrastructure and financial resources are lacking, and most developing countries still lack affordable internet access or efficient electronic payment methods.</li>
</ul>
<p class="takeaway">Two people can both be called &ldquo;offline&rdquo; when the fix for one is a cheaper data plan and for the other a power grid.</p>
<p>Some argue there is a downside to being a knowledge worker at all, and that knowledge workers will be the first replaced by automation with information systems. There is a downside to overreliance on information systems.</p>
<p class="takeaway">What is not in dispute is that knowledge workers and information systems are now critical to the success of modern organizations, economies, and societies.</p>

<div class="activity" data-activity="dwFill"></div>

<h3>Globalization: what it opens and what it costs</h3>
<p>Beneath these trends sits <b>globalization</b> &mdash; the integration of economies throughout the world, enabled by innovation and technological progress, visible in the greater international movement of commodities, money, information, and labor. Falling transportation and telecommunication costs opened many opportunities for organizations; three of them drive the rest of this section:</p>
<ul class="list-tight">
<li><b>Cultures moved closer together</b>, fueled by movies, television, and other media &mdash; Netflix reaches many countries and major movies are increasingly international &mdash; creating shared understanding about norms of behavior and desirable goods. The counterweight: the same technology has facilitated an increase in authoritarianism and restrictions on the free flow of communication and content, such as on WeChat and TikTok.</li>
<li><b>New markets appeared</b>, because the rapid rise of a new middle class in many developing countries lets established companies sell to millions of new customers.</li>
<li><b>The talent pool went global</b>, because with communication costs falling a company can draw on skilled professionals anywhere. Russia, China, and India offer high-quality education, and some countries built industries around one competency &mdash; software development and tax preparation in India, call centers in Ireland.</li>
</ul>
<p>That third opportunity has a name. <b>Outsourcing</b> is the moving of business processes or tasks &mdash; such as accounting, manufacturing, or security &mdash; to another company or another country. Companies do it for eight reasons, and cost is only one of the eight:</p>
<ul class="split">
<li>To reduce or control costs.</li>
<li>To free up internal resources.</li>
<li>To gain access to world-class capabilities.</li>
<li>To increase revenue potential.</li>
<li>To reduce time to market.</li>
<li>To increase process efficiencies.</li>
<li>To focus on core activities.</li>
<li>To compensate for a lack of specific skills.</li>
</ul>
<p>India&rsquo;s Wipro and Infosys lead in IT services, and even the reading of X-rays is outsourced by U.S. hospitals to skilled radiologists abroad, often while doctors in the United States are sleeping.</p>
<p>Then the bill arrives, in three parts:</p>
<ul class="keys">
<li><b>Governmental challenges</b> &mdash; differences in political systems, regulatory environments, laws, standards, or individual freedoms, so what is routine at home may be forbidden there.</li>
<li><b>Geoeconomic challenges</b> &mdash; differences in infrastructure, demographics, welfare, or workers&rsquo; expertise.</li>
<li><b>Cultural challenges</b> &mdash; differences in languages, beliefs, attitudes, religions, or life focus, including differing viewpoints regarding intellectual property.</li>
</ul>
<p>So locations must be chosen carefully, weighing English proficiency, salaries, and geopolitical risk. Singapore, Canada, and Ireland are declining because of rising salaries, pushing outsourcers toward emerging countries such as Bulgaria, Egypt, Ghana, Bangladesh, or Vietnam.</p>
<div class="callout warn"><p>Time zones cut both ways: the reason a hospital can have X-rays read overnight is the reason a project team loses a day waiting on an answer &mdash; the deciders are asleep while you work.</p></div>

<div class="activity" data-activity="dwSort"></div>

<h3>The societal issues information systems collide with</h3>
<p>The rapid development of transportation and telecommunication technologies, national and global infrastructures, and information systems has created a number of pressing societal issues. Three very different groups discuss them as interrelated societal &ldquo;megatrends&rdquo; tied to ever-increasing globalization:</p>
<ul class="split">
<li>Consulting firms such as PricewaterhouseCoopers (PwC) and Ernst &amp; Young (EY), who sell advice about them.</li>
<li>Local and national governments, who must legislate around them.</li>
<li>Political and business leaders at the World Economic Forum.</li>
</ul>
<p>They interact with, affect, and fuel one another, so none of them can be managed on its own; the chain is easy to trace:</p>
<ol class="steps">
<li>An aging population in one region and a population boom in another change migration.</li>
<li>Migration feeds the growth of cities, and about half the world&rsquo;s population now lives in one.</li>
<li>Cities consume resources, pressing on limited supplies of fossil fuels and other natural resources.</li>
</ol>

<div class="activity" data-activity="dwExplore"></div>

<p>Technology stands on both sides of these problems. Breakthroughs and transformations enabled by technology disrupt traditional business models &mdash; Uber wreaked havoc on the taxi industry &mdash; but can also help address pressing societal issues.</p>
<p>Medicine shows how far the systems now reach: professionals in the medical industry use <b>healthcare IS</b>, information systems that support healthcare processes ranging from patient diagnosis and treatment to analyzing patient and disease data to running doctors&rsquo; offices and hospitals.</p>
<div class="callout tip"><p>Put each new technology through three questions: who gains access, what work crosses a border because of it, and which societal issue it eases or worsens. That turns a gadget into a management decision.</p></div>

<div class="activity" data-activity="dwQuiz2"></div>
`;

ACT.dwQuiz1 = {
  kind: "quiz",
  label: "Check yourself",
  title: "The post-PC era, the cycle, and the knowledge society",
  how: "Pick the option that matches how the chapter actually describes each idea, then read every explanation.",
  objective: "1.1",
  questions: [
    {
      q: "The chapter says we are living in the <b>post-PC era</b>. What does that mean?",
      opts: [
        "The PC is finished as a work machine, so an organization can issue every employee one mobile device and cover every task with it.",
        "Connected devices, smartphones, and tablets are replacing traditional desktops and laptops, and new and old form factors work in tandem.",
        "It is another name for the move to cloud computing, so what changed is where files and applications live rather than which devices people use.",
        "Computing shifted toward social and casual activity, which is why tablets remain consumer devices rather than professional tools."
      ],
      a: 1,
      why: [
        "This is the one-device version of the idea, and it is what people usually mean when they say the PC is dead. The chapter says devices with newer form factors work in tandem with older ones, providing different devices for different users and different tasks, which is why a warehouse runs on tablets while a design studio still runs on workstations. It would be right if it said mobile devices are becoming the first thing people reach for.",
        "Correct. The chapter defines the post-PC era as connected devices, smartphones, and tablets replacing traditional desktop and laptop computers, with newer and older form factors complementing each other because not the device but the services and data provided are of primary importance.",
        "Cloud computing is real, related, and named separately in the chapter (Gmail, Microsoft 365, Dropbox) as what lets you reach email, files, and notes from different devices. But it answers where the data and applications sit, while the post-PC era answers which devices people carry and use, so the chapter treats cloud computing as an enabler of the shift rather than the shift itself.",
        "The first half is right: computing changed from an activity primarily focused on automating work to one that also carries social and casual activity. The second half contradicts the chapter, which says tablets began as consumer devices and are now commonplace in warehouses, showrooms, airplane cockpits, and hospitals."
      ]
    },
    {
      q: "What does the chapter mean by calling the relationship between technology and society a <b>virtuous cycle</b> &mdash; or a <b>vicious cycle</b>?",
      opts: [
        "Technology drives society in one direction: new devices change how people live, but how people live has no real effect on what gets built next.",
        "The virtuous cycle is the helpful technology and the vicious cycle is the harmful technology, so they refer to two different groups of devices.",
        "Technological change produces societal change and societal change reshapes technology; the same loop turns vicious when work invades leisure time.",
        "Companies must keep upgrading their information systems as competitors upgrade theirs, so falling behind for even one cycle costs market share."
      ],
      a: 2,
      why: [
        "This is the one-way version of the story, and it is the most common mistake here. The chapter makes the causation run in both directions: changes in technology enabled new ways of working and socializing, and then the blurring of work and leisure led employees to demand devices that support both and to bring their own devices into the workplace. It would be right only if what people wanted never changed what gets built next.",
        "It is one cycle viewed two ways, not two sets of devices. Mobility and connectivity are simultaneously the convenience and the reason people feel permanently on call; the label depends on whether you are describing the benefit or the cost of the same loop.",
        "Correct. The chapter describes a loop in which technological change produces societal change, which in turn shapes further technological change, and it offers 'vicious' as the same loop judged by the creep of work into people's leisure time.",
        "This describes competitive pressure to adopt technology, which is a real idea in this course, but it is about firms racing each other rather than technology and society reshaping one another. It would answer a question about competitive advantage instead."
      ]
    },
    {
      q: "Drucker argued that in a <b>knowledge society</b>, possessing knowledge would be as important as possessing land, labor, or capital. Which evidence does the chapter offer for that claim?",
      opts: [
        "Knowledge workers now make up roughly three quarters of the workforce in the United States and other developed nations.",
        "2023 Census survey data show median earnings of US$67,256 for bachelor's degree holders versus US$39,428 for high school graduates.",
        "The UPS delivery person uses GPS to take the best route, and the farmer in Iowa flies a drone to monitor soil conditions and crop yield.",
        "A college degree raises an individual worker's pay, which is exactly what a median earnings figure reports."
      ],
      a: 1,
      why: [
        "The direction is right but the size is wrong: the chapter says knowledge workers make up about a quarter of the workforce in the United States and other developed nations, with their numbers rising quickly. The separate claim that almost every worker can now be considered a knowledge worker is about how the work has spread, not about that percentage.",
        "Correct. The chapter cites the U.S. Census Bureau's American Community Survey (2023 data): US$86,524 for a graduate or professional degree, US$67,256 for a bachelor's degree, US$39,428 for a high school diploma, and US$31,660 without a high school diploma, and it notes the gap is increasing.",
        "Every word of this is in the chapter, which is what makes it tempting, but it is evidence for a different claim. Those two examples show that traditional occupations now use information systems too, which is why the line between knowledge workers and manual workers is blurring. They say nothing about knowledge being worth as much as land, labor, or capital; the earnings comparison is what carries that argument.",
        "This misreads what a median is. A median is the midpoint of a whole group, so it compares two populations rather than predicting what any one person would earn. It would be right if it said degree holders as a group earn more at the midpoint than non-degree holders as a group."
      ]
    }
  ]
};

ACT.dwFill = {
  kind: "fill",
  label: "Complete it",
  title: "The vocabulary of the knowledge society",
  how: "Choose the word or phrase the chapter uses in each sentence; the explanation appears once you pick.",
  objective: "1.1",
  blanks: [
    {
      before: "Professionals who are relatively well educated and who create, modify, and/or synthesize knowledge as a fundamental part of their jobs are ",
      after: ", a term Peter Drucker coined in 1959.",
      choices: ["manual workers", "knowledge workers", "learning workers"],
      a: 1,
      why: "Drucker coined knowledge worker; manual worker is the category the chapter contrasts it with, and learning worker is the future role the chapter says everyone must grow into."
    },
    {
      before: "Drucker predicted that as those workers grew in number and influence, a ",
      after: " would emerge, with education as its cornerstone and knowledge as important as land, labor, or capital.",
      choices: ["knowledge society", "digital divide", "global supply chain"],
      a: 0,
      why: "Knowledge society is Drucker's own term; the chapter notes others call the same thing the knowledge economy, the new economy, the digital society, the network era, or the internet era, and that this book calls it the digital world."
    },
    {
      before: "Knowledge workers currently make up about ",
      after: " of the workforce in the United States and other developed nations, and their numbers are rising quickly.",
      choices: ["half", "three quarters", "a quarter"],
      a: 2,
      why: "The chapter's figure is about a quarter, which is easy to overestimate because the chapter separately says the lines between knowledge workers and manual workers are blurring."
    },
    {
      before: "The gap between those who have access to information systems and those who do not is the ",
      after: ", which the chapter calls one of the major ethical challenges facing society today.",
      choices: ["digital divide", "knowledge economy", "geoeconomic challenge"],
      a: 0,
      why: "It counts as an ethical challenge because of the strong linkage between computer literacy and a person's ability to compete in the digital world, not merely because it is inconvenient."
    },
    {
      before: "Inside America that gap is rapidly shrinking, but people in rural communities, the elderly, people with disabilities, and minorities still lag behind national averages for internet access and ",
      after: ".",
      choices: ["median earnings", "computer literacy", "smartphone ownership"],
      a: 1,
      why: "The chapter pairs internet access with computer literacy because having a connection and knowing how to use it are two separate barriers, and closing only one leaves the divide open."
    },
    {
      before: "In most developing countries the obstacles are much harder to overcome, because infrastructure and financial resources are lacking and modern informational resources such as affordable internet access or ",
      after: " are missing.",
      choices: ["free public Wi-Fi", "government data portals", "efficient electronic payment methods"],
      a: 2,
      why: "The chapter names affordable internet access and efficient electronic payment methods specifically, which is why the divide abroad is an economic and infrastructure problem rather than a device problem."
    },
    {
      before: "Because what will matter most is not the knowledge itself but the knowledge of how to learn, the chapter says workers of the future need to become ",
      after: ".",
      choices: ["learning workers", "systems analysts", "data entry clerks"],
      a: 0,
      why: "Learning worker is the chapter's forward-looking term; systems analyst and data entry clerk are examples of how narrowly people once pictured computer-related occupations."
    }
  ]
};

ACT.dwSort = {
  kind: "sort",
  label: "Sort",
  title: "The digital divide and globalization: accurate or a common misconception?",
  how: "Drop each statement into the bucket where it belongs, then read why the chapter puts it there.",
  objective: "1.1",
  buckets: [
    { id: "true", name: "Accurate", hint: "matches what the chapter actually says" },
    { id: "myth", name: "Common misconception", hint: "sounds reasonable, but the chapter says otherwise" }
  ],
  items: [
    {
      t: "The digital divide in America is rapidly shrinking, yet rural communities, the elderly, people with disabilities, and minorities still lag national averages.",
      b: "true",
      why: "The chapter reports both halves at once: real national progress, and specific groups still behind on internet access and computer literacy."
    },
    {
      t: "The digital divide is essentially about who can afford the newest smartphone.",
      b: "myth",
      why: "It is about access to information systems and the computer literacy that lets a person compete at all; a new phone with no affordable connection, no payment system, and no skills does not close it."
    },
    {
      t: "Outside developed countries the gap widens, because many developing countries lack affordable internet access and efficient electronic payment methods.",
      b: "true",
      why: "The chapter attributes the wider gap to missing infrastructure and financial resources rather than to individual choices."
    },
    {
      t: "Outsourcing means moving business processes or tasks to another company, which may or may not be in another country.",
      b: "true",
      why: "The chapter's definition covers both: moving processes such as accounting, manufacturing, or security to another company or another country."
    },
    {
      t: "Companies outsource mainly to pay lower wages, so cost is the reason that really matters.",
      b: "myth",
      why: "Reducing or controlling costs is one of eight listed reasons, alongside freeing internal resources, gaining world-class capabilities, increasing revenue potential, reducing time to market, increasing process efficiencies, focusing on core activities, and compensating for missing skills."
    },
    {
      t: "U.S. hospitals outsource the reading of X-rays to skilled radiologists abroad, often while doctors in the United States are sleeping.",
      b: "true",
      why: "The chapter uses this to show that even highly specialized professional services, not just routine tasks, can move across borders."
    },
    {
      t: "Once a company has compared labor costs across countries, it has the information it needs to pick an outsourcing location.",
      b: "myth",
      why: "Location choice also involves governmental challenges (political systems, regulation, laws, individual freedoms), geoeconomic challenges (infrastructure, demographics, welfare, expertise), and cultural challenges (language, beliefs, religion, views on intellectual property), plus English proficiency and geopolitical risk."
    },
    {
      t: "Singapore, Canada, and Ireland are declining as outsourcing destinations because salaries there are rising, pushing outsourcers toward Bulgaria, Egypt, Ghana, Bangladesh, or Vietnam.",
      b: "true",
      why: "The chapter treats the outsourcing map as something that keeps moving, which is why an outsourcing decision has to be revisited rather than made once."
    },
    {
      t: "Globalization pushes cultures apart, since every country now produces media for its own audience.",
      b: "myth",
      why: "The chapter says the reverse: movies, television, and other media have moved cultures closer together, creating shared understanding about norms, desirable goods and services, and even forms of government."
    },
    {
      t: "Spreading internet access reliably expands the free flow of communication in the countries it reaches.",
      b: "myth",
      why: "The chapter notes the same technology has facilitated an increase in authoritarianism and restrictions on the free flow of communication and content, naming WeChat and TikTok."
    }
  ]
};

ACT.dwExplore = {
  kind: "explore",
  label: "Explore",
  title: "The societal issues of the digital world",
  how: "Open each issue and read all four panels; the last panel is the part managers underestimate.",
  objective: "1.1",
  labels: ["What it is", "Where you can see it", "Why it matters now", "What makes it hard"],
  items: [
    {
      icon: "DEM",
      name: "Demographic changes",
      sub: "Population structure",
      what: "Changes in the structure of populations related to factors such as age, birth rates, and migration.",
      real: "Many countries in the developed world see rapidly aging populations, while developing regions such as Africa are expected to rise rapidly in population, fueling massive global population growth.",
      absent: "These differences shift the balance of demand and supply of labor, so the workers an organization needs and the customers it sells to are increasingly in different places.",
      why: "Differences in welfare are likely to keep increasing, and many countries are already experiencing both positive and negative effects of mass migrations, making this a political problem as much as an economic one."
    },
    {
      icon: "URB",
      name: "Urbanization",
      sub: "Rural to urban",
      what: "The movement of rural populations to urban areas.",
      real: "50 percent of the world's population is now living in cities, and cities are where the chapter's own public-infrastructure examples sit, such as adaptive traffic control systems and variable speed limits.",
      absent: "Every additional city dweller needs housing, transport, water, and power inside the same square miles, so density turns ordinary services into engineering problems.",
      why: "Sustaining that growth while providing livable environments for the inhabitants will pose major challenges, and the growth does not pause while the solutions are being built."
    },
    {
      icon: "ECO",
      name: "Shifts in economic power",
      sub: "Where the leverage sits",
      what: "Changes in countries' purchasing power and control over natural resources.",
      real: "Established economies are losing their dominating positions in the world's economy, while a new middle class in developing countries becomes a market of millions of new customers.",
      absent: "Where purchasing power sits determines which markets a company must serve and which countries set the terms of trade it has to accept.",
      why: "The chapter notes the shift results in the need to resolve political struggles, and political struggle is exactly the governmental challenge that makes operating across borders risky."
    },
    {
      icon: "RES",
      name: "Resource scarcity",
      sub: "Finite supply",
      what: "Pressure created by the limited availability of fossil fuels and other natural resources.",
      real: "Population growth, global trade, consumerism, and other factors contribute to increasing waste and pollution as well as a growing need for resources.",
      absent: "Humans already live beyond the finite natural resources the planet can provide, so demand and supply are moving in opposite directions rather than converging.",
      why: "Scarcity is entangled with every other issue on this list: more people, in more cities, with more purchasing power, all need more of the same finite materials."
    },
    {
      icon: "CLI",
      name: "Climate change",
      sub: "Long-term shifts",
      what: "Large-scale, long-term shifts in regional and global temperatures and weather patterns.",
      real: "Changing weather patterns, a rise in sea levels, and an increase in the severity of storms.",
      absent: "These pose many challenges for individuals, societies, and the world, including for any organization whose stores, factories, or supply routes sit in the path of a storm.",
      why: "The chapter is careful about scope here: the consequences arrive regardless of what one concludes about the causes, so an organization still has to plan around them."
    },
    {
      icon: "SUS",
      name: "Sustainable development",
      sub: "Present versus future",
      what: "Development that meets the needs of the present without compromising the ability of future generations to meet their own needs.",
      real: "The wording is the World Commission on Environment and Development's, from 1987, and the chapter attaches it to every issue above it: waste, pollution, and the need for resources keep rising while the planet's supply is finite.",
      absent: "The chapter says it will become an increasingly important aspect, which turns a moral argument into a test a manager can apply to a proposal: does this option leave the next generation the same range of choices?",
      why: "The needs of the present are concrete and loud while the needs of future generations are abstract and silent, which is why the trade-off usually gets decided in favor of the present."
    }
  ]
};

ACT.dwQuiz2 = {
  kind: "quiz",
  label: "Check yourself",
  title: "Globalization, societal issues, and healthcare IS",
  how: "Answer each question, then read all four explanations before moving on.",
  objective: "1.1",
  questions: [
    {
      q: "A U.S. hospital sends overnight X-ray images to skilled radiologists in another country to be read while American doctors sleep. Which term does the chapter use for this specific arrangement?",
      opts: [
        "Globalization, which the chapter defines as the practice of hiring workers in lower-wage countries.",
        "Outsourcing, which shows that even highly specialized professional services can move to another company or country.",
        "The digital divide, because the country receiving the work has less access to information systems.",
        "A geoeconomic challenge, because the arrangement rests on differences in infrastructure, welfare, and workers' expertise between the two countries."
      ],
      a: 1,
      why: [
        "Globalization is the right family but the wrong definition. The chapter defines globalization as the integration of economies throughout the world, enabled by innovation and technological progress; outsourcing is one activity that integration makes possible. This would be right if it defined globalization properly and called the X-ray example an instance of it.",
        "Correct. Outsourcing is the moving of business processes or tasks to another company or another country, and the chapter uses radiology precisely to show that even highly specialized services are candidates.",
        "The digital divide is the gap between those with and those without access to information systems. It is a separate idea, and it does not fit here: the radiologists reading these images clearly have access to advanced systems.",
        "Geoeconomic challenges are genuinely differences in infrastructure, demographics, welfare, or workers' expertise, so the words fit the situation. But the chapter uses that term for the difficulties an organization has to manage once it operates across borders, not as a name for the practice of moving the work. It would be right if the question asked what makes choosing this location risky."
      ]
    },
    {
      q: "The chapter quotes a 1987 definition of <b>sustainable development</b>. Which statement matches it?",
      opts: [
        "Growth a company can maintain year after year without losing market share to competitors.",
        "Reducing waste through recycling programs so that materials are reused rather than discarded.",
        "Development that meets the needs of the present without compromising the ability of future generations to meet their own needs.",
        "Economic activity that avoids fossil fuels, since fossil fuels are the resource the chapter says is running short."
      ],
      a: 2,
      why: [
        "This is the everyday business sense of 'sustainable' meaning repeatable, and it is the most common mix-up. The chapter's definition is about generations rather than quarters, and this option would be right in a discussion of business strategy instead of societal issues.",
        "Recycling is one practice that can serve sustainable development, but the definition is broader: it covers every kind of development, including energy, housing, and agriculture, and it states a constraint on the future rather than a technique in the present.",
        "Correct. That is the World Commission on Environment and Development's 1987 wording, quoted in the chapter, which presents it as an increasingly important standard as resource scarcity and climate change intensify.",
        "Fossil fuels appear in the chapter under resource scarcity, and using fewer of them may serve sustainable development, but the definition never names any specific resource. It would be right if it were offered as one example of sustainable development rather than as its definition."
      ]
    },
    {
      q: "How does the chapter define <b>healthcare IS</b>?",
      opts: [
        "Information systems supporting healthcare processes, from diagnosis and treatment to analyzing patient data to running offices and hospitals.",
        "Software that lets patients look up symptoms, view test results, and book appointments online.",
        "The medical equipment itself, such as cardiac monitors and imaging machines, once it has been connected to a network and is sending its readings somewhere to be stored.",
        "A specialization within computer science that prepares programmers to build software for hospitals."
      ],
      a: 0,
      why: [
        "Correct. The chapter's definition deliberately spans clinical work, analysis, and administration, which is why healthcare IS shows information systems reaching all the way into a traditional profession rather than being a single product.",
        "This is the patient-facing slice only. Patient portals are part of healthcare IS, but the definition also covers diagnosis and treatment, the analysis of patient and disease data, and the running of doctors' offices and hospitals, so this option is too narrow.",
        "Devices are hardware. An information system includes the technology, the data, and the people and processes that use it; a cardiac monitor generates data that a healthcare IS then stores, analyzes, and routes to a physician.",
        "This describes a field of study and the people trained in it, not a system. Healthcare IS refers to the systems themselves, which are used by professionals in the medical industry rather than only by programmers."
      ]
    }
  ]
};
